name: Gated Build Check

on:
  pull_request:
    branches: ['main', 'development']
    
jobs:
  build:
    name: Build Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Build
        run: dotnet build src/Utilities.Text.sln
      - name: Run Unit Tests
        run: dotnet test src/Utilities.Text.sln
